server:
  port: 8082
spring:
  application:
    name: kafka-consumer

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: usergrp
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.example.kafka.model



